/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mocks from "./mocks";
export type { mocks };
export type { DotlySubscription } from "./DotlySubscription";
export type { MockUSDC } from "./MockUSDC";
