import { Metadata } from 'next'
import { notFound } from 'next/navigation'
import Image from 'next/image'
import { PoweredByDotly } from '@/components/PoweredByDotly'
import { getServerApiUrl } from '@/lib/server-api'
import { CardView } from './CardView'
import type { CardTemplate, SocialPlatform, MediaBlockType } from '@dotly/types'

export const revalidate = 0

const API_URL = getServerApiUrl()
const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://dotly.one'

interface TeamBrand {
  brandName: string | null
  brandLogoUrl: string | null
  brandColor: string | null
  hideDotlyBranding: boolean
}

interface RawCard {
  id: string
  handle: string
  templateId: string
  fields: Record<string, string>
  isActive: boolean
  theme?: {
    primaryColor?: string
    secondaryColor?: string
    fontFamily?: string
    backgroundUrl?: string
    logoUrl?: string
    buttonStyle?: string
    socialButtonStyle?: string
  }
  socialLinks?: Array<{ id: string; platform: string; url: string; displayOrder: number }>
  mediaBlocks?: Array<{
    id: string
    type: string
    url?: string | null
    caption?: string
    altText?: string
    linkUrl?: string
    displayOrder: number
    mimeType?: string | null
    fileSize?: number | null
    groupId?: string | null
    groupName?: string | null
  }>
  teamBrand?: TeamBrand | null
}

/** Validate that a value is a safe CSS hex color (e.g. #fff or #0ea5e9) */
function safeBrandColor(color: string | null | undefined): string | null {
  if (!color) return null
  return /^#[0-9a-fA-F]{3,8}$/.test(color) ? color : null
}

/**
 * Fetch a card by handle.
 * Next.js 15 automatically deduplicates fetch() calls to the same URL
 * within the same render pass, so generateMetadata and the page component
 * share one network request transparently.
 */
async function getCard(handle: string): Promise<RawCard | null> {
  try {
    const res = await fetch(`${API_URL}/public/cards/${handle}`)
    if (!res.ok) return null
    return (await res.json()) as RawCard
  } catch {
    return null
  }
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ handle: string }>
}): Promise<Metadata> {
  const { handle } = await params
  const card = await getCard(handle)
  if (!card) return { title: 'Card Not Found' }

  const fields = card.fields
  const name = fields.name ?? 'Digital Card'
  const title = `${name} — Dotly.one`
  const canonicalUrl = `${SITE_URL}/card/${encodeURIComponent(handle)}`

  // Build a clean description: bio, or "Title at Company", or just the name
  const description =
    fields.bio?.slice(0, 160) ??
    (fields.title && fields.company
      ? `${fields.title} at ${fields.company}`
      : (fields.title ?? fields.company ?? `${name}'s digital business card on Dotly.one`))

  // Dynamic OG image — generated by /api/og?handle=...
  // The route pre-fetches the avatar and embeds it as a data URI so Satori
  // never makes cross-origin requests at render time (fixes WhatsApp crawlers).
  const ogImageUrl = `${SITE_URL}/api/og?handle=${encodeURIComponent(handle)}`
  const ogImages = [
    {
      url: ogImageUrl,
      secureUrl: ogImageUrl,
      width: 1200,
      height: 630,
      alt: name,
      type: 'image/png',
    },
  ]

  // JSON-LD structured data (Person / ProfilePage)
  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'ProfilePage',
    name: title,
    url: canonicalUrl,
    mainEntity: {
      '@type': 'Person',
      name,
      ...(fields.title ? { jobTitle: fields.title } : {}),
      ...(fields.company ? { worksFor: { '@type': 'Organization', name: fields.company } } : {}),
      ...(fields.email ? { email: fields.email } : {}),
      ...(fields.phone ? { telephone: fields.phone } : {}),
      ...(fields.website ? { url: fields.website } : {}),
      ...(fields.avatarUrl ? { image: fields.avatarUrl } : {}),
    },
  }

  return {
    title,
    description,
    alternates: {
      canonical: canonicalUrl,
    },
    openGraph: {
      title: name,
      description,
      url: canonicalUrl,
      images: ogImages,
      type: 'profile',
      siteName: 'Dotly.one',
    },
    twitter: {
      card: 'summary_large_image',
      title: name,
      description,
      images: ogImages.map((img) => img.url),
    },
  }
}

export default async function CardPage({ params }: { params: Promise<{ handle: string }> }) {
  const { handle } = await params
  // `getCard` is cached — this reuses the same response already fetched by generateMetadata
  const rawCard = await getCard(handle)
  if (!rawCard) notFound()

  const theme = rawCard.theme ?? {
    primaryColor: '#0ea5e9',
    secondaryColor: '#ffffff',
    fontFamily: 'Inter',
  }

  const teamBrand = rawCard.teamBrand ?? null
  const fields = rawCard.fields

  const card = {
    id: rawCard.id,
    handle: rawCard.handle,
    templateId: rawCard.templateId as CardTemplate,
    isActive: rawCard.isActive,
    fields: {
      name: fields.name ?? '',
      title: fields.title ?? '',
      company: fields.company ?? '',
      phone: fields.phone ?? '',
      whatsapp: fields.whatsapp ?? '',
      email: fields.email ?? '',
      website: fields.website ?? '',
      bio: fields.bio ?? '',
      address: fields.address ?? '',
      mapUrl: fields.mapUrl ?? '',
      avatarUrl: fields.avatarUrl ?? '',
      logoUrl: fields.logoUrl ?? '',
    },
  }

  const cardTheme = {
    primaryColor: safeBrandColor(teamBrand?.brandColor) ?? theme.primaryColor ?? '#0ea5e9',
    secondaryColor: theme.secondaryColor ?? '#ffffff',
    fontFamily: theme.fontFamily ?? 'Inter',
    backgroundUrl: theme.backgroundUrl,
    logoUrl: theme.logoUrl,
    buttonStyle: (theme.buttonStyle ?? 'filled-icon-text') as import('@dotly/types').ButtonStyle,
    socialButtonStyle: (theme.socialButtonStyle ??
      'follow') as import('@dotly/types').SocialButtonStyle,
  }

  const socialLinks = (rawCard.socialLinks ?? []).map(
    (l: { id: string; platform: string; url: string; displayOrder: number }) => ({
      id: l.id,
      platform: l.platform as SocialPlatform,
      url: l.url,
      displayOrder: l.displayOrder,
    }),
  )

  const mediaBlocks = (rawCard.mediaBlocks ?? []).map(
    (b: {
      id: string
      type: string
      url?: string | null
      caption?: string
      altText?: string
      linkUrl?: string
      displayOrder: number
      mimeType?: string | null
      fileSize?: number | null
      groupId?: string | null
      groupName?: string | null
    }) => ({
      id: b.id,
      type: b.type as MediaBlockType,
      url: b.url ?? null,
      caption: b.caption,
      altText: b.altText,
      linkUrl: b.linkUrl,
      displayOrder: b.displayOrder,
      mimeType: b.mimeType ?? undefined,
      fileSize: b.fileSize ?? undefined,
      groupId: b.groupId ?? undefined,
      groupName: b.groupName ?? undefined,
    }),
  )

  const brandColor = safeBrandColor(teamBrand?.brandColor)
  const canonicalUrl = `${SITE_URL}/card/${encodeURIComponent(handle)}`

  // JSON-LD structured data injected into the page <head>
  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'ProfilePage',
    name: `${fields.name ?? 'Digital Card'} — Dotly.one`,
    url: canonicalUrl,
    mainEntity: {
      '@type': 'Person',
      name: fields.name ?? 'Digital Card',
      ...(fields.title ? { jobTitle: fields.title } : {}),
      ...(fields.company ? { worksFor: { '@type': 'Organization', name: fields.company } } : {}),
      ...(fields.email ? { email: fields.email } : {}),
      ...(fields.phone ? { telephone: fields.phone } : {}),
      ...(fields.website ? { url: fields.website } : {}),
      ...(fields.avatarUrl ? { image: fields.avatarUrl } : {}),
    },
  }

  return (
    <main
      className="min-h-screen flex flex-col items-center"
      style={{
        // Subtle neutral-to-slate gradient canvas — templates render full-width inside
        background: 'linear-gradient(160deg, #f8fafc 0%, #f1f5f9 50%, #e2e8f0 100%)',
      }}
    >
      {/* JSON-LD structured data */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />

      {/* Team brand color as CSS custom property */}
      {brandColor && <style>{`:root { --brand-color: ${brandColor}; }`}</style>}

      {/* Constrained content column — max-w-md keeps the card phone-width */}
      <div className="w-full max-w-md flex flex-col min-h-screen">
        {/* Team logo — shown above the card when team has a brand logo */}
        {teamBrand?.brandLogoUrl && (
          <div className="flex justify-center pt-8 pb-4 px-4">
            <Image
              src={teamBrand.brandLogoUrl}
              alt={teamBrand.brandName ?? 'Team logo'}
              width={160}
              height={40}
              className="h-10 w-auto object-contain"
            />
          </div>
        )}

        {/* Card — fills the column, no extra horizontal padding */}
        <div className="flex-1">
          <CardView
            card={card}
            theme={cardTheme}
            socialLinks={socialLinks}
            mediaBlocks={mediaBlocks}
            mode="web"
            cardHandle={rawCard.handle}
            ownerName={fields.name ?? 'this person'}
          />
        </div>

        <PoweredByDotly hideDotlyBranding={teamBrand?.hideDotlyBranding ?? false} />
      </div>
    </main>
  )
}
