import { Metadata } from 'next'
import { notFound } from 'next/navigation'
import Image from 'next/image'
import { PoweredByDotly } from '@/components/PoweredByDotly'
import { getServerApiUrl } from '@/lib/server-api'
import { CardView } from './CardView'
import type {
  CardTemplate,
  SocialPlatform,
  MediaBlockType,
  CardActionsConfig,
  CardServiceOffer,
  CardStoreProduct,
} from '@dotly/types'

export const revalidate = 0

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://dotly.one'

interface TeamBrand {
  brandName: string | null
  brandLogoUrl: string | null
  brandColor: string | null
  secondaryColor: string | null
  fontFamily: string | null
  brandLock: boolean
  hideDotlyBranding: boolean
}

interface RawCard {
  id: string
  handle: string
  templateId: string
  fields: Record<string, unknown>
  isActive: boolean
  vcardPolicy?: string
  theme?: {
    primaryColor?: string
    secondaryColor?: string
    fontFamily?: string
    backgroundUrl?: string
    logoUrl?: string
    buttonStyle?: string
    socialButtonStyle?: string
  }
  socialLinks?: Array<{ id: string; platform: string; url: string; displayOrder: number }>
  mediaBlocks?: Array<{
    id: string
    type: string
    url?: string | null
    caption?: string
    altText?: string
    linkUrl?: string
    displayOrder: number
    mimeType?: string | null
    fileSize?: number | null
    groupId?: string | null
    groupName?: string | null
  }>
  teamBrand?: TeamBrand | null
  bookableAppointment?: {
    slug: string
    name: string
    durationMins: number
  } | null
}

function stringField(fields: Record<string, unknown>, key: string): string {
  const value = fields[key]
  return typeof value === 'string' ? value : ''
}

/** Validate that a value is a safe CSS hex color (e.g. #fff or #0ea5e9) */
function safeBrandColor(color: string | null | undefined): string | null {
  if (!color) return null
  return /^#[0-9a-fA-F]{3,8}$/.test(color) ? color : null
}

/**
 * Fetch a card by handle.
 * Next.js 15 automatically deduplicates fetch() calls to the same URL
 * within the same render pass, so generateMetadata and the page component
 * share one network request transparently.
 */
async function getCard(handle: string): Promise<RawCard | null> {
  const apiUrl = getServerApiUrl()
  const res = await fetch(`${apiUrl}/public/cards/${handle}`)
  if (res.status === 404) return null
  if (!res.ok) {
    throw new Error(`Failed to load card (${res.status})`)
  }
  return (await res.json()) as RawCard
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ handle: string }>
}): Promise<Metadata> {
  const { handle } = await params
  const card = await getCard(handle)
  if (!card) return { title: 'Card Not Found' }

  const fields = card.fields
  const name = stringField(fields, 'name') || 'Digital Card'
  const title = `${name} — Dotly.one`
  const canonicalUrl = `${SITE_URL}/card/${encodeURIComponent(handle)}`
  const bio = stringField(fields, 'bio')
  const roleTitle = stringField(fields, 'title')
  const company = stringField(fields, 'company')
  const email = stringField(fields, 'email')
  const phone = stringField(fields, 'phone')
  const website = stringField(fields, 'website')
  const avatarUrl = stringField(fields, 'avatarUrl')

  // Build a clean description: bio, or "Title at Company", or just the name
  const description =
    bio.slice(0, 160) ||
    (roleTitle && company
      ? `${roleTitle} at ${company}`
      : roleTitle || company || `${name}'s customer funnel on Dotly.one`)

  // Dynamic OG image — generated by /api/og?handle=...
  // The route pre-fetches the avatar and embeds it as a data URI so Satori
  // never makes cross-origin requests at render time (fixes WhatsApp crawlers).
  const ogImageUrl = `${SITE_URL}/api/og?handle=${encodeURIComponent(handle)}`
  const ogImages = [
    {
      url: ogImageUrl,
      secureUrl: ogImageUrl,
      width: 1200,
      height: 630,
      alt: name,
      type: 'image/png',
    },
  ]

  // JSON-LD structured data (Person / ProfilePage)
  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'ProfilePage',
    name: title,
    url: canonicalUrl,
    mainEntity: {
      '@type': 'Person',
      name,
      ...(roleTitle ? { jobTitle: roleTitle } : {}),
      ...(company ? { worksFor: { '@type': 'Organization', name: company } } : {}),
      ...(email ? { email } : {}),
      ...(phone ? { telephone: phone } : {}),
      ...(website ? { url: website } : {}),
      ...(avatarUrl ? { image: avatarUrl } : {}),
    },
  }

  return {
    title,
    description,
    alternates: {
      canonical: canonicalUrl,
    },
    openGraph: {
      title: name,
      description,
      url: canonicalUrl,
      images: ogImages,
      type: 'profile',
      siteName: 'Dotly.one',
    },
    twitter: {
      card: 'summary_large_image',
      title: name,
      description,
      images: ogImages.map((img) => img.url),
    },
  }
}

export default async function CardPage({ params }: { params: Promise<{ handle: string }> }) {
  const { handle } = await params
  // `getCard` is cached — this reuses the same response already fetched by generateMetadata
  const rawCard = await getCard(handle)
  if (!rawCard) notFound()

  const theme = rawCard.theme ?? {
    primaryColor: '#0ea5e9',
    secondaryColor: '#ffffff',
    fontFamily: 'Inter',
  }

  const teamBrand = rawCard.teamBrand ?? null
  const fields = rawCard.fields as Record<string, unknown>
  const name = stringField(fields, 'name') || 'Digital Card'
  const roleTitle = stringField(fields, 'title')
  const company = stringField(fields, 'company')
  const email = stringField(fields, 'email')
  const phone = stringField(fields, 'phone')
  const website = stringField(fields, 'website')
  const avatarUrl = stringField(fields, 'avatarUrl')
  const teamBrandPrimary = safeBrandColor(teamBrand?.brandColor)
  const teamBrandSecondary = safeBrandColor(teamBrand?.secondaryColor)
  const teamBrandLocked = teamBrand?.brandLock ?? false

  const card = {
    id: rawCard.id,
    handle: rawCard.handle,
    templateId: rawCard.templateId as CardTemplate,
    isActive: rawCard.isActive,
    fields: {
      name: stringField(fields, 'name'),
      title: stringField(fields, 'title'),
      company: stringField(fields, 'company'),
      phone: stringField(fields, 'phone'),
      whatsapp: stringField(fields, 'whatsapp'),
      email: stringField(fields, 'email'),
      website: stringField(fields, 'website'),
      bio: stringField(fields, 'bio'),
      address: stringField(fields, 'address'),
      mapUrl: stringField(fields, 'mapUrl'),
      avatarUrl: stringField(fields, 'avatarUrl'),
      logoUrl: stringField(fields, 'logoUrl'),
      bookingAppointmentSlug: stringField(fields, 'bookingAppointmentSlug') || undefined,
      actions: fields.actions as CardActionsConfig | undefined,
      services: Array.isArray(fields.services)
        ? (fields.services as CardServiceOffer[])
        : undefined,
      products: Array.isArray(fields.products)
        ? (fields.products as CardStoreProduct[])
        : undefined,
    },
  }

  const cardTheme = {
    primaryColor:
      (teamBrandLocked ? teamBrandPrimary : null) ??
      teamBrandPrimary ??
      theme.primaryColor ??
      '#0ea5e9',
    secondaryColor:
      (teamBrandLocked ? teamBrandSecondary : null) ?? theme.secondaryColor ?? '#ffffff',
    fontFamily: (teamBrandLocked ? teamBrand?.fontFamily : null) ?? theme.fontFamily ?? 'Inter',
    backgroundUrl: theme.backgroundUrl,
    logoUrl: (teamBrandLocked ? teamBrand?.brandLogoUrl : null) ?? theme.logoUrl,
    buttonStyle: (theme.buttonStyle ?? 'filled-icon-text') as import('@dotly/types').ButtonStyle,
    socialButtonStyle: (theme.socialButtonStyle ??
      'follow') as import('@dotly/types').SocialButtonStyle,
  }

  const socialLinks = (rawCard.socialLinks ?? []).map(
    (l: { id: string; platform: string; url: string; displayOrder: number }) => ({
      id: l.id,
      platform: l.platform as SocialPlatform,
      url: l.url,
      displayOrder: l.displayOrder,
    }),
  )

  const mediaBlocks = (rawCard.mediaBlocks ?? []).map(
    (b: {
      id: string
      type: string
      url?: string | null
      caption?: string
      altText?: string
      linkUrl?: string
      displayOrder: number
      mimeType?: string | null
      fileSize?: number | null
      groupId?: string | null
      groupName?: string | null
    }) => ({
      id: b.id,
      type: b.type as MediaBlockType,
      url: b.url ?? null,
      caption: b.caption,
      altText: b.altText,
      linkUrl: b.linkUrl,
      displayOrder: b.displayOrder,
      mimeType: b.mimeType ?? undefined,
      fileSize: b.fileSize ?? undefined,
      groupId: b.groupId ?? undefined,
      groupName: b.groupName ?? undefined,
    }),
  )

  const brandColor = teamBrandPrimary
  const canonicalUrl = `${SITE_URL}/card/${encodeURIComponent(handle)}`

  // JSON-LD structured data injected into the page <head>
  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'ProfilePage',
    name: `${name} — Dotly.one`,
    url: canonicalUrl,
    mainEntity: {
      '@type': 'Person',
      name,
      ...(roleTitle ? { jobTitle: roleTitle } : {}),
      ...(company ? { worksFor: { '@type': 'Organization', name: company } } : {}),
      ...(email ? { email } : {}),
      ...(phone ? { telephone: phone } : {}),
      ...(website ? { url: website } : {}),
      ...(avatarUrl ? { image: avatarUrl } : {}),
    },
  }

  return (
    <main
      className="min-h-screen flex flex-col items-center"
      style={{
        // Subtle neutral-to-slate gradient canvas — templates render full-width inside
        background: 'linear-gradient(160deg, #f8fafc 0%, #f1f5f9 50%, #e2e8f0 100%)',
      }}
    >
      {/* JSON-LD structured data */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />

      {/* Team brand color as CSS custom property */}
      {brandColor && <style>{`:root { --brand-color: ${brandColor}; }`}</style>}

      {/* Constrained content column — max-w-md keeps the card phone-width */}
      <div className="w-full max-w-md flex flex-col min-h-screen">
        {/* Team logo — shown above the card when team has a brand logo */}
        {teamBrand?.brandLogoUrl && (
          <div className="flex justify-center pt-8 pb-4 px-4">
            <Image
              src={teamBrand.brandLogoUrl}
              alt={teamBrand.brandName ?? 'Team logo'}
              width={160}
              height={40}
              className="h-10 w-auto object-contain"
            />
          </div>
        )}

        {/* Card — fills the column, no extra horizontal padding */}
        <div className="flex-1">
          <CardView
            card={card}
            theme={cardTheme}
            socialLinks={socialLinks}
            mediaBlocks={mediaBlocks}
            mode="web"
            cardHandle={rawCard.handle}
            ownerName={name}
            vcardPolicy={(rawCard.vcardPolicy ?? 'PUBLIC') as 'PUBLIC' | 'MEMBERS_ONLY'}
            bookableAppointment={rawCard.bookableAppointment ?? null}
          />
        </div>

        <PoweredByDotly hideDotlyBranding={teamBrand?.hideDotlyBranding ?? false} />
      </div>
    </main>
  )
}
